/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Change Password */
        post: operations["admin_change_password_api_v1_admin_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Login */
        post: operations["admin_login_api_v1_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Logout */
        post: operations["admin_logout_api_v1_admin_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Me */
        get: operations["admin_me_api_v1_admin_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/availability/{window_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Admin Update Availability
         * @description Bulk update every size for one harvest window in a single call (SPEC §8).
         */
        put: operations["admin_update_availability_api_v1_admin_availability__window_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Customers */
        get: operations["admin_list_customers_api_v1_admin_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Customer */
        get: operations["admin_get_customer_api_v1_admin_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Dashboard
         * @description Counts for the dashboard cards. Cheap aggregate queries only.
         */
        get: operations["admin_dashboard_api_v1_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/fish-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Fish Types */
        get: operations["admin_list_fish_types_api_v1_admin_fish_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/fish-types/{fish_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Update Fish Type */
        patch: operations["admin_update_fish_type_api_v1_admin_fish_types__fish_type_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/harvest-windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Harvest Windows */
        get: operations["admin_list_harvest_windows_api_v1_admin_harvest_windows_get"];
        put?: never;
        /** Admin Create Harvest Window */
        post: operations["admin_create_harvest_window_api_v1_admin_harvest_windows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/harvest-windows/{window_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Update Harvest Window */
        patch: operations["admin_update_harvest_window_api_v1_admin_harvest_windows__window_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Messages */
        get: operations["admin_list_messages_api_v1_admin_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Update Message */
        patch: operations["admin_update_message_api_v1_admin_messages__message_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Orders */
        get: operations["admin_list_orders_api_v1_admin_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Export Orders Csv
         * @description CSV export honouring exactly the same filters as the list endpoint (SPEC §8).
         */
        get: operations["admin_export_orders_csv_api_v1_admin_orders_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Order */
        get: operations["admin_get_order_api_v1_admin_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Admin Update Order
         * @description Internal notes and assignment. The caller's `version` guards against lost updates.
         */
        patch: operations["admin_update_order_api_v1_admin_orders__order_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Record Payment */
        post: operations["admin_record_payment_api_v1_admin_orders__order_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Create Quote */
        post: operations["admin_create_quote_api_v1_admin_orders__order_id__quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}/quote/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Accept Quote */
        post: operations["admin_accept_quote_api_v1_admin_orders__order_id__quote_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Transition Order */
        post: operations["admin_transition_order_api_v1_admin_orders__order_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Settings */
        get: operations["admin_list_settings_api_v1_admin_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Update Setting */
        patch: operations["admin_update_setting_api_v1_admin_settings__key__patch"];
        trace?: never;
    };
    "/api/v1/admin/size-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Size Classes */
        get: operations["admin_list_size_classes_api_v1_admin_size_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/size-classes/{size_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Update Size Class */
        patch: operations["admin_update_size_class_api_v1_admin_size_classes__size_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Users */
        get: operations["admin_list_users_api_v1_admin_users_get"];
        put?: never;
        /** Admin Create User */
        post: operations["admin_create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{admin_user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Update User */
        patch: operations["admin_update_user_api_v1_admin_users__admin_user_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description Verify the callback, create the account session and return to a relative `next`.
         */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Start
         * @description Begin the OIDC authorization-code + PKCE flow (Addendum §A4).
         *
         *     `client=mobile` runs the same Google flow but, on success, hands a single-use auth code
         *     back to the app's `redirect_uri` (validated against `MOBILE_REDIRECT_ALLOWLIST`).
         */
        get: operations["google_start_api_v1_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Logout */
        post: operations["auth_logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Me */
        get: operations["auth_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mobile/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mobile Token
         * @description Exchange a single-use mobile auth code for a bearer session token.
         */
        post: operations["mobile_token_api_v1_auth_mobile_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Contact Message */
        post: operations["create_contact_message_api_v1_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cart
         * @description Return the signed-in account's cart; an untouched cart is version 0 with no lines.
         */
        get: operations["get_cart_api_v1_me_cart_get"];
        /**
         * Put Cart
         * @description Replace the cart contents; a stale `expected_version` is rejected with 409.
         */
        put: operations["put_cart_api_v1_me_cart_put"];
        post?: never;
        /**
         * Delete Cart
         * @description Empty the cart. Deleting an already-empty cart is a no-op, not an error.
         */
        delete: operations["delete_cart_api_v1_me_cart_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Orders
         * @description Third access path for My Orders: orders attached to the signed-in account.
         */
        get: operations["my_orders_api_v1_me_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/orders/attach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach Order
         * @description Attach a guest order to the signed-in account using reference + phone (A4).
         */
        post: operations["attach_order_api_v1_me_orders_attach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Order */
        post: operations["submit_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lookup Order */
        post: operations["lookup_order_api_v1_orders_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order Details */
        get: operations["get_order_details_api_v1_orders__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{reference}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Order */
        post: operations["cancel_order_api_v1_orders__reference__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountMeResponse */
        AccountMeResponse: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /**
             * Signed In
             * @default true
             */
            signed_in: boolean;
        };
        /** AccountOrderItem */
        AccountOrderItem: {
            /** Fish Type */
            fish_type: string;
            /** Fulfilment */
            fulfilment: string;
            /** Indicative Total Kobo */
            indicative_total_kobo?: number | null;
            /** Indicative Unit Price Kobo */
            indicative_unit_price_kobo?: number | null;
            /** Is Bulk */
            is_bulk: boolean;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["OrderItemPublic"][];
            /**
             * Preferred Date
             * Format: date
             */
            preferred_date: string;
            /** Quantity Kg */
            quantity_kg: number;
            quote?: components["schemas"]["OrderQuotePublic"] | null;
            /** Reference */
            reference: string;
            /** Size Label */
            size_label: string;
            /** Status */
            status: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Time Slot Label */
            time_slot_label: string;
        };
        /** AccountOrdersResponse */
        AccountOrdersResponse: {
            /** Csrf Token */
            csrf_token?: string | null;
            /** Orders */
            orders: components["schemas"]["AccountOrderItem"][];
        };
        /**
         * AdminAvailabilityUpdate
         * @description Bulk update every size for one harvest window in a single call (SPEC §8).
         */
        AdminAvailabilityUpdate: {
            /** Indicative Prices Per Kg Kobo */
            indicative_prices_per_kg_kobo?: {
                [key: string]: number | null;
            };
            /** Statuses */
            statuses?: {
                [key: string]: "limited" | "available" | "main_stock" | "sold_out" | "unavailable";
            };
        };
        /** AdminChangePasswordRequest */
        AdminChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** AdminCountsByStatus */
        AdminCountsByStatus: {
            /**
             * Cancelled
             * @default 0
             */
            cancelled: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /**
             * Confirmed
             * @default 0
             */
            confirmed: number;
            /**
             * Declined
             * @default 0
             */
            declined: number;
            /**
             * Expired
             * @default 0
             */
            expired: number;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Quoted
             * @default 0
             */
            quoted: number;
            /**
             * Ready
             * @default 0
             */
            ready: number;
        };
        /** AdminCustomerDetail */
        AdminCustomerDetail: {
            /** Email */
            email?: string | null;
            /**
             * First Order At
             * Format: date-time
             */
            first_order_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Order Count
             * @default 0
             */
            order_count: number;
            /**
             * Orders
             * @default []
             */
            orders: components["schemas"]["AdminOrderListItem"][];
            /** Phone E164 */
            phone_e164: string;
            /**
             * Total Kg
             * @default 0
             */
            total_kg: number;
        };
        /** AdminCustomerOut */
        AdminCustomerOut: {
            /** Email */
            email?: string | null;
            /**
             * First Order At
             * Format: date-time
             */
            first_order_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Order Count
             * @default 0
             */
            order_count: number;
            /** Phone E164 */
            phone_e164: string;
            /**
             * Total Kg
             * @default 0
             */
            total_kg: number;
        };
        /** AdminDashboardResponse */
        AdminDashboardResponse: {
            counts_by_status: components["schemas"]["AdminCountsByStatus"];
            /**
             * Outbox Counts
             * @default {}
             */
            outbox_counts: {
                [key: string]: number;
            };
            /**
             * Today Deliveries
             * @default 0
             */
            today_deliveries: number;
            /**
             * Today Pickups
             * @default 0
             */
            today_pickups: number;
            /**
             * Unhandled Messages
             * @default 0
             */
            unhandled_messages: number;
            /**
             * Upcoming Bulk Orders
             * @default 0
             */
            upcoming_bulk_orders: number;
            /**
             * Week Confirmed Volume Kg
             * @default 0
             */
            week_confirmed_volume_kg: number;
        };
        /** AdminFishTypeOut */
        AdminFishTypeOut: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Image Path */
            image_path: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
        };
        /** AdminFishTypeUpdate */
        AdminFishTypeUpdate: {
            /** Description */
            description?: string | null;
            /** Image Path */
            image_path?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** AdminHarvestWindowIn */
        AdminHarvestWindowIn: {
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /**
             * Is Published
             * @default false
             */
            is_published: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
        };
        /** AdminHarvestWindowOut */
        AdminHarvestWindowOut: {
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Id */
            id: string;
            /** Is Published */
            is_published: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
        };
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            /** Csrf Token */
            csrf_token: string;
            /**
             * Must Change Password
             * @default false
             */
            must_change_password: boolean;
            user: components["schemas"]["AdminUserSummary"];
        };
        /** AdminMeResponse */
        AdminMeResponse: {
            /** Csrf Token */
            csrf_token?: string | null;
            /**
             * Signed In
             * @default true
             */
            signed_in: boolean;
            user: components["schemas"]["AdminUserSummary"];
        };
        /** AdminMessageOut */
        AdminMessageOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Status */
            status: string;
        };
        /** AdminMessageUpdate */
        AdminMessageUpdate: {
            /**
             * Status
             * @default handled
             * @enum {string}
             */
            status: "new" | "handled";
        };
        /** AdminOrderDetail */
        AdminOrderDetail: {
            /** Allowed Next Statuses */
            allowed_next_statuses: string[];
            /** Assigned To */
            assigned_to?: string | null;
            /**
             * Balance Kobo
             * @default 0
             */
            balance_kobo: number;
            /** Closed At */
            closed_at?: string | null;
            /** Customer Email */
            customer_email?: string | null;
            /** Customer Name */
            customer_name: string;
            /** Customer Notes */
            customer_notes?: string | null;
            /** Customer Phone */
            customer_phone: string;
            /** Delivery Address */
            delivery_address?: string | null;
            /** Delivery Landmark */
            delivery_landmark?: string | null;
            /**
             * Due Kobo
             * @default 0
             */
            due_kobo: number;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["OrderEventPublic"][];
            /** Fish Type */
            fish_type: string;
            /** Fulfilment */
            fulfilment: string;
            /** Id */
            id: string;
            /** Internal Notes */
            internal_notes?: string | null;
            /** Is Bulk */
            is_bulk: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Paid Kobo
             * @default 0
             */
            paid_kobo: number;
            /**
             * Payments
             * @default []
             */
            payments: components["schemas"]["AdminPaymentOut"][];
            /**
             * Preferred Date
             * Format: date
             */
            preferred_date: string;
            /** Quantity Kg */
            quantity_kg: number;
            /**
             * Quotes
             * @default []
             */
            quotes: components["schemas"]["AdminQuoteOut"][];
            /** Reference */
            reference: string;
            /** Size Label */
            size_label: string;
            /** Source Intent */
            source_intent?: string | null;
            /** Status */
            status: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Time Slot Label */
            time_slot_label: string;
            /** Version */
            version: number;
        };
        /** AdminOrderListItem */
        AdminOrderListItem: {
            /** Customer Name */
            customer_name: string;
            /** Customer Phone */
            customer_phone: string;
            /** Fish Type */
            fish_type: string;
            /** Fulfilment */
            fulfilment: string;
            /** Id */
            id: string;
            /** Is Bulk */
            is_bulk: boolean;
            /**
             * Preferred Date
             * Format: date
             */
            preferred_date: string;
            /** Quantity Kg */
            quantity_kg: number;
            /** Reference */
            reference: string;
            /** Size Label */
            size_label: string;
            /** Status */
            status: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Time Slot Label */
            time_slot_label: string;
            /** Version */
            version: number;
        };
        /** AdminOrderListResponse */
        AdminOrderListResponse: {
            /** Orders */
            orders: components["schemas"]["AdminOrderListItem"][];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 25
             */
            page_size: number;
            /** Total */
            total: number;
        };
        /** AdminOrderUpdateRequest */
        AdminOrderUpdateRequest: {
            /** Assigned To */
            assigned_to?: string | null;
            /** Internal Notes */
            internal_notes?: string | null;
            /** Version */
            version: number;
        };
        /** AdminPaymentOut */
        AdminPaymentOut: {
            /** Amount Kobo */
            amount_kobo: number;
            /** Id */
            id: string;
            /** Method */
            method: string;
            /** Note */
            note?: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Reference */
            reference?: string | null;
        };
        /** AdminPaymentRequest */
        AdminPaymentRequest: {
            /** Amount Kobo */
            amount_kobo: number;
            /**
             * Method
             * @default cash
             * @enum {string}
             */
            method: "cash" | "transfer" | "pos" | "other";
            /** Note */
            note?: string | null;
            /** Received At */
            received_at?: string | null;
            /** Reference */
            reference?: string | null;
        };
        /** AdminPaymentResponse */
        AdminPaymentResponse: {
            /** Balance Kobo */
            balance_kobo: number;
            /** Due Kobo */
            due_kobo: number;
            /** Paid Kobo */
            paid_kobo: number;
            payment: components["schemas"]["AdminPaymentOut"];
        };
        /** AdminQuoteAcceptRequest */
        AdminQuoteAcceptRequest: {
            /** Quote Id */
            quote_id: string;
        };
        /** AdminQuoteOut */
        AdminQuoteOut: {
            /** Accepted At */
            accepted_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delivery Fee Kobo */
            delivery_fee_kobo: number;
            /** Deposit Kobo */
            deposit_kobo: number;
            /** Discount Kobo */
            discount_kobo: number;
            /** Id */
            id: string;
            /** Message To Customer */
            message_to_customer?: string | null;
            /** Quantity Kg */
            quantity_kg: number;
            /** Status */
            status: string;
            /** Total Kobo */
            total_kobo: number;
            /** Unit Price Kobo */
            unit_price_kobo: number;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
            /** Version No */
            version_no: number;
        };
        /** AdminQuoteRequest */
        AdminQuoteRequest: {
            /**
             * Delivery Fee Kobo
             * @default 0
             */
            delivery_fee_kobo: number;
            /**
             * Deposit Kobo
             * @default 0
             */
            deposit_kobo: number;
            /**
             * Discount Kobo
             * @default 0
             */
            discount_kobo: number;
            /** Message To Customer */
            message_to_customer?: string | null;
            /** Quantity Kg */
            quantity_kg: number;
            /** Unit Price Kobo */
            unit_price_kobo: number;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
        };
        /** AdminQuoteResponse */
        AdminQuoteResponse: {
            /**
             * Balance Kobo
             * @default 0
             */
            balance_kobo: number;
            /**
             * Due Kobo
             * @default 0
             */
            due_kobo: number;
            /**
             * Paid Kobo
             * @default 0
             */
            paid_kobo: number;
            quote: components["schemas"]["AdminQuoteOut"];
        };
        /** AdminSettingsResponse */
        AdminSettingsResponse: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** AdminSettingsUpdate */
        AdminSettingsUpdate: {
            /** Value */
            value: string;
        };
        /** AdminSizeClassOut */
        AdminSizeClassOut: {
            /** Descriptor */
            descriptor: string;
            /** Id */
            id: string;
            /** Image Path */
            image_path: string;
            /** Is Active */
            is_active: boolean;
            /** Is Featured */
            is_featured: boolean;
            /** Is Smoking Size */
            is_smoking_size: boolean;
            /** Label */
            label: string;
            /** Max Kg */
            max_kg: string | null;
            /** Min Kg */
            min_kg: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
        };
        /** AdminSizeClassUpdate */
        AdminSizeClassUpdate: {
            /** Descriptor */
            descriptor?: string | null;
            /** Image Path */
            image_path?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Featured */
            is_featured?: boolean | null;
            /** Is Smoking Size */
            is_smoking_size?: boolean | null;
            /** Label */
            label?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** AdminTransitionRequest */
        AdminTransitionRequest: {
            /** Note */
            note?: string | null;
            /** To Status */
            to_status: string;
            /** Version */
            version: number;
        };
        /** AdminUserCreate */
        AdminUserCreate: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default staff
             * @enum {string}
             */
            role: "owner" | "staff";
        };
        /** AdminUserSummary */
        AdminUserSummary: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /** Must Change Password */
            must_change_password: boolean;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** AdminUserUpdate */
        AdminUserUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
            /** Password */
            password?: string | null;
            /** Role */
            role?: ("owner" | "staff") | null;
        };
        /** AttachOrderRequest */
        AttachOrderRequest: {
            /** Phone */
            phone: string;
            /** Reference */
            reference: string;
        };
        /** AttachOrderResponse */
        AttachOrderResponse: {
            /** Attached */
            attached: boolean;
            /** Reference */
            reference: string;
            /** Status */
            status: string;
        };
        /** CartLine */
        CartLine: {
            /** Fish Type */
            fish_type: string;
            /** Indicative Unit Price Kobo */
            indicative_unit_price_kobo?: number | null;
            /** Line Total Kobo */
            line_total_kobo?: number | null;
            /** Quantity Kg */
            quantity_kg: number;
            /** Size */
            size: string;
            /** Size Label */
            size_label: string;
        };
        /** CartLineInput */
        CartLineInput: {
            /**
             * Fish Type
             * @enum {string}
             */
            fish_type: "clarias" | "hybrid" | "any";
            /** Quantity Kg */
            quantity_kg: number;
            /** Size */
            size: string;
        };
        /** CartResponse */
        CartResponse: {
            /** Indicative Total Kobo */
            indicative_total_kobo?: number | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["CartLine"][];
            /** Updated At */
            updated_at?: string | null;
            /** Version */
            version: number;
        };
        /** CartUpdateRequest */
        CartUpdateRequest: {
            /** Expected Version */
            expected_version: number;
            /** Items */
            items: components["schemas"]["CartLineInput"][];
        };
        /** CatalogResponse */
        CatalogResponse: {
            /** Fish Types */
            fish_types: components["schemas"]["FishTypePublic"][];
            harvest_window: components["schemas"]["HarvestWindowPublic"] | null;
            settings: components["schemas"]["CatalogSettingsPublic"];
            /** Size Classes */
            size_classes: components["schemas"]["SizeClassPublic"][];
        };
        /** CatalogSettingsPublic */
        CatalogSettingsPublic: {
            /** Announcement Banner */
            announcement_banner: string | null;
            /** Business Hours */
            business_hours: string[];
            /** Delivery Notice */
            delivery_notice: string;
            /** Farm Address */
            farm_address: string;
            /** Farm Maps Url */
            farm_maps_url: string | null;
            /** Max Order Kg */
            max_order_kg: number;
            /** Min Lead Days */
            min_lead_days: number;
            /** Min Order Kg */
            min_order_kg: number;
            /** Phone Number */
            phone_number: string;
            /** Time Slots */
            time_slots: components["schemas"]["TimeSlotPublic"][];
            /** Whatsapp Number */
            whatsapp_number: string;
        };
        /** ContactMessageCreate */
        ContactMessageCreate: {
            /** Message */
            message: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Turnstile Token */
            turnstile_token?: string | null;
            /** Website */
            website?: string | null;
        };
        /** ContactMessageCreated */
        ContactMessageCreated: {
            /**
             * Status
             * @default received
             * @constant
             */
            status: "received";
        };
        /** FishTypePublic */
        FishTypePublic: {
            /** Description */
            description: string;
            /** Image Path */
            image_path: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarvestWindowPublic */
        HarvestWindowPublic: {
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Notes */
            notes: string | null;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
        };
        /** MobileTokenRequest */
        MobileTokenRequest: {
            /** Code */
            code: string;
            /** Code Verifier */
            code_verifier: string;
        };
        /** MobileTokenResponse */
        MobileTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
        };
        /** OrderCancelResponse */
        OrderCancelResponse: {
            /** Reference */
            reference: string;
            /** Status */
            status: string;
        };
        /** OrderCreateRequest */
        OrderCreateRequest: {
            /** Customer Name */
            customer_name: string;
            /**
             * Delivery Address
             * @default
             */
            delivery_address: string | null;
            /**
             * Delivery Landmark
             * @default
             */
            delivery_landmark: string | null;
            /**
             * Email
             * @default
             */
            email: string | null;
            /** Fish Type */
            fish_type?: ("clarias" | "hybrid" | "any") | null;
            /**
             * Fulfilment
             * @enum {string}
             */
            fulfilment: "pickup" | "delivery";
            /** Items */
            items?: components["schemas"]["OrderItemInput"][] | null;
            /**
             * Notes
             * @default
             */
            notes: string | null;
            /** Phone */
            phone: string;
            /**
             * Preferred Date
             * Format: date
             */
            preferred_date: string;
            /** Quantity Kg */
            quantity_kg?: number | null;
            /** Size */
            size?: string | null;
            /** Source Intent */
            source_intent?: string | null;
            /** Time Slot */
            time_slot: string;
            /** Turnstile Token */
            turnstile_token?: string | null;
            /** Website */
            website?: string | null;
        };
        /** OrderCreateResponse */
        OrderCreateResponse: {
            /** Access Token */
            access_token: string;
            /** Indicative Total Kobo */
            indicative_total_kobo: number | null;
            /** Indicative Unit Price Kobo */
            indicative_unit_price_kobo: number | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["OrderItemPublic"][];
            /** Reference */
            reference: string;
            /** Status */
            status: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** OrderEventPublic */
        OrderEventPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** From Status */
            from_status?: string | null;
            /** Note */
            note?: string | null;
            /** To Status */
            to_status: string;
            /** Type */
            type: string;
        };
        /**
         * OrderItemInput
         * @description One requested line of a multi-line order.
         *
         *     The same per-line rules as the legacy single-line payload apply (known fish type, a
         *     catalog size slug, a positive kilogram quantity). Prices are never accepted from the
         *     client; the server fills them in.
         */
        OrderItemInput: {
            /**
             * Fish Type
             * @enum {string}
             */
            fish_type: "clarias" | "hybrid" | "any";
            /** Quantity Kg */
            quantity_kg: number;
            /** Size */
            size: string;
        };
        /**
         * OrderItemPublic
         * @description A public order line. `size_label` is the label snapshotted at submission time.
         */
        OrderItemPublic: {
            /** Fish Type */
            fish_type: string;
            /** Indicative Unit Price Kobo */
            indicative_unit_price_kobo?: number | null;
            /** Line Total Kobo */
            line_total_kobo?: number | null;
            /** Quantity Kg */
            quantity_kg: number;
            /** Size Label */
            size_label: string;
        };
        /** OrderLookupRequest */
        OrderLookupRequest: {
            /** Phone */
            phone: string;
            /** Reference */
            reference: string;
        };
        /** OrderLookupResponse */
        OrderLookupResponse: {
            /** Access Token */
            access_token: string;
            order: components["schemas"]["OrderPublic"];
        };
        /** OrderPublic */
        OrderPublic: {
            /** Customer Email */
            customer_email?: string | null;
            /** Customer Name */
            customer_name: string;
            /** Customer Phone Masked */
            customer_phone_masked: string;
            /** Delivery Address */
            delivery_address?: string | null;
            /** Delivery Landmark */
            delivery_landmark?: string | null;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["OrderEventPublic"][];
            /** Fish Type */
            fish_type: string;
            /** Fulfilment */
            fulfilment: string;
            /** Indicative Total Kobo */
            indicative_total_kobo?: number | null;
            /** Indicative Unit Price Kobo */
            indicative_unit_price_kobo?: number | null;
            /** Is Bulk */
            is_bulk: boolean;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["OrderItemPublic"][];
            /** Notes */
            notes?: string | null;
            /**
             * Preferred Date
             * Format: date
             */
            preferred_date: string;
            /** Quantity Kg */
            quantity_kg: number;
            quote?: components["schemas"]["OrderQuotePublic"] | null;
            /** Reference */
            reference: string;
            /** Size Label */
            size_label: string;
            /** Status */
            status: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Time Slot Label */
            time_slot_label: string;
        };
        /**
         * OrderQuotePublic
         * @description The quote as the customer sees it (SPEC §5.4 "quote breakdown when available").
         *
         *     Only the newest quote for an order is ever exposed. Superseded versions stay admin-only,
         *     and `created_by` is deliberately absent so an admin's identity never reaches a customer.
         */
        OrderQuotePublic: {
            /** Delivery Fee Kobo */
            delivery_fee_kobo: number;
            /** Deposit Kobo */
            deposit_kobo: number;
            /** Discount Kobo */
            discount_kobo: number;
            /** Is Expired */
            is_expired: boolean;
            /** Message To Customer */
            message_to_customer?: string | null;
            /** Quantity Kg */
            quantity_kg: number;
            /** Status */
            status: string;
            /** Total Kobo */
            total_kobo: number;
            /** Unit Price Kobo */
            unit_price_kobo: number;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
            /** Version No */
            version_no: number;
        };
        /** SizeClassPublic */
        SizeClassPublic: {
            /** Descriptor */
            descriptor: string;
            /** Image Path */
            image_path: string;
            /** Indicative Price Per Kg Kobo */
            indicative_price_per_kg_kobo: number | null;
            /** Is Featured */
            is_featured: boolean;
            /** Is Smoking Size */
            is_smoking_size: boolean;
            /** Label */
            label: string;
            /** Max Kg */
            max_kg: string | null;
            /** Min Kg */
            min_kg: string;
            /** Price Updated At */
            price_updated_at: string | null;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            /** Status */
            status: string;
        };
        /** TimeSlotPublic */
        TimeSlotPublic: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_change_password_api_v1_admin_auth_change_password_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_login_api_v1_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_logout_api_v1_admin_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    admin_me_api_v1_admin_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMeResponse"];
                };
            };
        };
    };
    admin_update_availability_api_v1_admin_availability__window_id__put: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                window_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAvailabilityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_customers_api_v1_admin_customers_get: {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCustomerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_customer_api_v1_admin_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_dashboard_api_v1_admin_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboardResponse"];
                };
            };
        };
    };
    admin_list_fish_types_api_v1_admin_fish_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFishTypeOut"][];
                };
            };
        };
    };
    admin_update_fish_type_api_v1_admin_fish_types__fish_type_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                fish_type_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminFishTypeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFishTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_harvest_windows_api_v1_admin_harvest_windows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHarvestWindowOut"][];
                };
            };
        };
    };
    admin_create_harvest_window_api_v1_admin_harvest_windows_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminHarvestWindowIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHarvestWindowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_harvest_window_api_v1_admin_harvest_windows__window_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                window_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminHarvestWindowIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHarvestWindowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_messages_api_v1_admin_messages_get: {
        parameters: {
            query?: {
                handled?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_message_api_v1_admin_messages__message_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminMessageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_orders_api_v1_admin_orders_get: {
        parameters: {
            query?: {
                status?: string | null;
                from?: string | null;
                to?: string | null;
                fulfilment?: string | null;
                size?: string | null;
                bulk?: boolean | null;
                search?: string | null;
                sort?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_export_orders_csv_api_v1_admin_orders_export_csv_get: {
        parameters: {
            query?: {
                status?: string | null;
                from?: string | null;
                to?: string | null;
                fulfilment?: string | null;
                size?: string | null;
                bulk?: boolean | null;
                search?: string | null;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_order_api_v1_admin_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_order_api_v1_admin_orders__order_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOrderUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_record_payment_api_v1_admin_orders__order_id__payments_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_quote_api_v1_admin_orders__order_id__quote_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminQuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_accept_quote_api_v1_admin_orders__order_id__quote_accept_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminQuoteAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_transition_order_api_v1_admin_orders__order_id__transition_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_settings_api_v1_admin_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsResponse"][];
                };
            };
        };
    };
    admin_update_setting_api_v1_admin_settings__key__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_size_classes_api_v1_admin_size_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSizeClassOut"][];
                };
            };
        };
    };
    admin_update_size_class_api_v1_admin_size_classes__size_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                size_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSizeClassUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSizeClassOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserSummary"][];
                };
            };
        };
    };
    admin_create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_user_api_v1_admin_users__admin_user_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path: {
                admin_user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_start_api_v1_auth_google_start_get: {
        parameters: {
            query?: {
                next?: string | null;
                client?: string | null;
                redirect_uri?: string | null;
                code_challenge?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    auth_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountMeResponse"];
                };
            };
        };
    };
    mobile_token_api_v1_auth_mobile_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MobileTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    create_contact_message_api_v1_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactMessageCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cart_api_v1_me_cart_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    put_cart_api_v1_me_cart_put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cart_api_v1_me_cart_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_orders_api_v1_me_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOrdersResponse"];
                };
            };
        };
    };
    attach_order_api_v1_me_orders_attach_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_order_api_v1_orders_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderLookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_details_api_v1_orders__reference__get: {
        parameters: {
            query?: never;
            header: {
                "X-Order-Token": string;
            };
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_v1_orders__reference__cancel_post: {
        parameters: {
            query?: never;
            header: {
                "X-Order-Token": string;
            };
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderCancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthcheck_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
