import { StyleSheet } from "react-native";

export const colors = {
    ink: "#17251F",
    muted: "#637268",
    forest: "#0B3D2A",
    leaf: "#0F5F3E",
    mint: "#E8F3EC",
    lime: "#8CC63F",
    amber: "#F6B93B",
    coral: "#D66A4A",
    paper: "#F7F8F3",
    white: "#FFFFFF",
    border: "#DFE6DF",
    danger: "#A83F32",
    dangerSoft: "#FBECE8",
    gray: "#758078",
};

export const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: colors.paper },
    content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 34, gap: 16 },
    heading: { color: colors.forest, fontSize: 28, fontWeight: "800" },
    subheading: { color: colors.ink, fontSize: 18, fontWeight: "700" },
    body: { color: colors.ink, fontSize: 16, lineHeight: 23 },
    muted: { color: colors.muted, fontSize: 14, lineHeight: 20 },
    panel: {
        backgroundColor: colors.white,
        borderColor: colors.border,
        borderWidth: 1,
        borderRadius: 10,
        padding: 16,
        gap: 12,
    },
    button: {
        minHeight: 52,
        paddingHorizontal: 18,
        borderRadius: 8,
        backgroundColor: colors.leaf,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 8,
    },
    buttonText: { color: colors.white, fontSize: 16, fontWeight: "700" },
    secondaryButton: {
        minHeight: 48,
        paddingHorizontal: 16,
        borderRadius: 8,
        borderColor: colors.border,
        borderWidth: 1,
        backgroundColor: colors.white,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 8,
    },
    secondaryButtonText: { color: colors.forest, fontSize: 15, fontWeight: "700" },
    disabled: { opacity: 0.55 },
    field: {
        minHeight: 48,
        paddingHorizontal: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.border,
        color: colors.ink,
        fontSize: 16,
        backgroundColor: colors.white,
    },
    row: { flexDirection: "row", alignItems: "center", gap: 10 },
    errorPanel: {
        backgroundColor: colors.dangerSoft,
        borderColor: "#EBC5BB",
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        gap: 8,
    },
    pill: { borderRadius: 20, alignSelf: "flex-start", paddingHorizontal: 10, paddingVertical: 5 },
});